mpa_admin_app/comments/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class CommentForm(FlaskForm):
  content = TextAreaField('Content', validators=[DataRequired()])
  submit = SubmitField('Post')

mpa_admin_app/events/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, DateField
from wtforms.validators import DataRequired

class EventForm(FlaskForm):
  title = StringField('Title', validators=[DataRequired()])
  content = TextAreaField('Content', validators=[DataRequired()])
  event_date = DateField('Event Date', validators=[DataRequired()])
  submit = SubmitField('Post Event')

mpa_admin_app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
  title = StringField('Title', validators=[DataRequired()])
  content = TextAreaField('Content', validators=[DataRequired()])
  code_snippet = TextAreaField('Code Snippet')
  submit = SubmitField('Post')

mpa_admin_app/roles/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class RoleForm(FlaskForm):
  title = StringField('Title', validators=[DataRequired()])
  description = TextAreaField('Description', validators=[DataRequired()])
  submit = SubmitField('Create Role')

mpa_admin_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from mpa_admin_app.config import Config


db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'

mail = Mail()


def create_app(config_class=Config):
  app = Flask(__name__)
  app.config.from_object(Config)

  db.init_app(app)
  bcrypt.init_app(app)
  login_manager.init_app(app)
  mail.init_app(app)

  from mpa_admin_app.main.routes import main
  from mpa_admin_app.users.routes import users
  from mpa_admin_app.posts.routes import posts
  from mpa_admin_app.events.routes import events
  from mpa_admin_app.members.routes import members
  from mpa_admin_app.roles.routes import roles
  from mpa_admin_app.comments.routes import comments
  from mpa_admin_app.api.routes import api
  from mpa_admin_app.errors.handlers import errors
  app.register_blueprint(main)
  app.register_blueprint(users)
  app.register_blueprint(posts)
  app.register_blueprint(events)
  app.register_blueprint(members)
  app.register_blueprint(roles)
  app.register_blueprint(comments)
  app.register_blueprint(api)
  app.register_blueprint(errors)

  return app

mpa_admin_app/comments/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from mpa_admin_app import db
from mpa_admin_app.models import Comment
from mpa_admin_app.comments.forms import CommentForm

comments = Blueprint('comments', __name__)


@comments.route("/comment/<int:post_id>", methods=['GET', 'POST'])
@login_required
def new_comment(post_id):
	comment = Comment(content=request.form['addComment'], post_id=post_id, author=current_user)
	path = request.form['path']
	db.session.add(comment)
	db.session.commit()
	flash('Your comment has been posted!', 'success')
	
	return redirect(path)


@comments.route("/comment/<int:comment_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_comment(comment_id):
	path = request.form['path']

	comment = Comment.query.get_or_404(comment_id)
	
	db.session.delete(comment)
	db.session.commit()
	flash('Your comment has been deleted!', 'success')
	
	return redirect(path)
		

mpa_admin_app/events/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from mpa_admin_app import db
from mpa_admin_app.models import Event
from mpa_admin_app.events.forms import EventForm

events = Blueprint('events', __name__)


@events.route("/event/new", methods=['GET', 'POST'])
@login_required
def new_event():
	eventForm = EventForm()
	if eventForm.validate_on_submit():
		path = request.form['path']
		event = Event(title = eventForm.title.data, content = eventForm.content.data, author=current_user, event_date = eventForm.event_date.data)
		db.session.add(event)
		db.session.commit()
		flash('Your event has been created!', 'success')
		
		return redirect(path)


@events.route("/event/<int:event_id>/update", methods=['GET', 'POST'])
@login_required
def update_event(event_id):
	event = Event.query.get_or_404(event_id)
	if event.author != current_user:
		abort(403)
	updateEvent = EventForm()
	if updateEvent.validate_on_submit():
		event.title = updateEvent.title.data
		event.content = updateEvent.content.data
		event.event_date = updateEvent.event_date.data
		db.session.commit()
		flash('Your event has been updated!', 'success')
		return redirect(url_for('events.event', event_id=event.id))
	elif request.method == 'GET':
		updateEvent.title.data = event.title
		updateEvent.content.data = event.content
		updateEvent.event_date.data = event.event_date
	return render_template('create_event.html', title='Update Event', form=updateEvent, legend='Update Event')


@events.route("/event/<int:event_id>/delete", methods=['POST'])
@login_required
def delete_event(event_id):
	path = request.form['path']

	event = Event.query.get_or_404(event_id)
	if event.author != current_user:
		abort(403)
	db.session.delete(event)
	db.session.commit()
	flash('Your event has been deleted!', 'success')
	return redirect(path)

mpa_admin_app/main/routes.py
from flask import Blueprint, render_template, request
from mpa_admin_app.models import Post, User, Event, Role, Comment
from mpa_admin_app.posts.forms import PostForm
from mpa_admin_app.events.forms import EventForm

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home", methods=['GET', 'POST'])
def home():
	# import ipdb; ipdb.set_trace()
	postForm = PostForm()
	eventForm = EventForm()
	page = request.args.get('page', 1, type=int)
	posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=10)
	users = User.query.all()
	events = Event.query.order_by(Event.event_date.desc()).all()
	comments = Comment.query.all()
	return render_template('home.html', title='Home', postForm=postForm, eventForm=eventForm, posts=posts, users=users, events=events, comments=comments)

mpa_admin_app/members/routes.py
from flask import Blueprint, render_template, request
from mpa_admin_app.models import Post, User, Event, Role

members = Blueprint('members', __name__)


@members.route("/members")
def membership():
	roles = Role.query.all()
	users = User.query.all()
	return render_template('members.html', title='Members', roles=roles, users=users)

mpa_admin_app/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from mpa_admin_app import db
from mpa_admin_app.models import Post, Comment
from mpa_admin_app.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
	postForm = PostForm()
	if postForm.validate_on_submit():
		path = request.form['path']
		post = Post(title = postForm.title.data, content = postForm.content.data, code_snippet = postForm.code_snippet.data, author=current_user)
		db.session.add(post)
		db.session.commit()
		flash('Your post has been created!', 'success')
		
		return redirect(path)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	updatePost = PostForm()
	if updatePost.validate_on_submit():
		post.title = updatePost.title.data
		post.content = updatePost.content.data
		post.code_snippet = updatePost.code_snippet.data
		db.session.commit()
		flash('Your post has been updated!', 'success')
		return redirect(url_for('main.home', post_id=post.id))
	elif request.method == 'GET':
		updatePost.title.data = post.title
		updatePost.content.data = post.content
		updatePost.code_snippet.data = post.code_snippet
	return render_template('create_post.html', title='Update Post', form=updatePost, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
	path = request.form['path']

	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	db.session.delete(post)
	db.session.commit()
	flash('Your post has been deleted!', 'success')
	return redirect(path)

mpa_admin_app/roles/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from mpa_admin_app import db
from mpa_admin_app.models import Role, User
from mpa_admin_app.roles.forms import RoleForm

roles = Blueprint('roles', __name__)


@roles.route("/role/new", methods=['GET', 'POST'])
@login_required
def new_role():
	roleForm = RoleForm()
	if roleForm.validate_on_submit():
		role = Role(title = roleForm.title.data, description = roleForm.description.data)
		db.session.add(role)
		db.session.commit()
		flash('Role has been created!', 'success')
		return redirect(url_for('members.membership'))
	return render_template('create_role.html', title='Create New Role', form=roleForm, legend='New Role')


@roles.route("/role/<int:role_id>/update", methods=['GET', 'POST'])
@login_required
def update_role(role_id):
	role = Role.query.get_or_404(role_id)
	if current_user.user_role != 1:
		abort(403)
	updateRole = RoleForm()
	if updateRole.validate_on_submit():
		role.title = updateRole.title.data
		role.description = updateRole.description.data
		role.permissions = updateRole.permissions.data
		db.session.commit()
		flash('Your role has been updated!', 'success')
		return redirect(url_for('roles.role_page', role_id=role.id))
	elif request.method == 'GET':
		updateRole.title.data = role.title
		updateRole.description.data = role.description
		updateRole.permissions.data = role.permissions
	return render_template('create_role.html', title='Update Role', form=updateRole, legend='Update Role')


@roles.route("/role/<int:role_id>/delete", methods=['POST'])
@login_required
def delete_role(role_id):
	role = Role.query.get_or_404(role_id)
	if current_user.user_role != 1:
		abort(403)
	if role.title == 'admin' or role.title == 'visitor':
		flash('You cannot delete ADMIN or VISITOR role!', 'danger')
	db.session.delete(role)
	db.session.commit()
	flash('Your role has been deleted!', 'success')
	return redirect(url_for('members.membership'))

mpa_admin_app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, jsonify, abort
from flask_login import login_user, current_user, logout_user, login_required
from datetime import datetime
from mpa_admin_app import db, bcrypt
from mpa_admin_app.models import User, Post, Comment, Event
from mpa_admin_app.posts.forms import PostForm
from mpa_admin_app.events.forms import EventForm
from mpa_admin_app.users.forms import (RegistrationForm, LoginForm, UpdateProfileForm,
                                   RequestResetForm, ResetPasswordForm)
from mpa_admin_app.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	registrationForm = RegistrationForm()
	if registrationForm.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(registrationForm.password.data).decode('utf-8')
		user = User(username=registrationForm.username.data, email=registrationForm.email.data, password=hashed_password)
		db.session.add(user)
		db.session.commit()
		flash('Your account has been created! You are now able to log in', 'success')
		return redirect(url_for('users.login'))
	return render_template('register.html', title='Register', form=registrationForm)


@users.route("/login", methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	loginForm = LoginForm()
	if loginForm.validate_on_submit():
		user = User.query.filter_by(username=loginForm.username.data).first()
		if user and user.user_role == 'admin' and bcrypt.check_password_hash(user.password, loginForm.password.data):
			login_user(user, remember=loginForm.remember.data)
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		else:
			flash('Login Unsuccessful. Please check username and password... and just an FYI, only admins can access this awesome app 😉', 'danger')
	return render_template('login.html', title='Login', form=loginForm)


@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('main.home'))


@users.route("/profile/<int:id>", methods=['GET', 'POST'])
@login_required
def profile(id):
	postForm = PostForm()
	eventForm = EventForm()
	user = User.query.filter_by(id=id).first()
	posts = Post.query.order_by(Post.date_posted.desc()).filter_by(author=user).all()
	comments = Comment.query.all()
	events = Event.query.order_by(Event.event_date.desc()).all()
	updateForm = UpdateProfileForm()
	if updateForm.validate_on_submit():
		if updateForm.picture.data:
			picture_file = save_picture(updateForm.picture.data)
			current_user.image_file = picture_file
		current_user.username = updateForm.username.data
		current_user.email = updateForm.email.data
		db.session.commit()
		flash('Your profile has been updated!', 'success')
		return redirect(url_for('users.profile', id=id))
	elif request.method == 'GET':
		updateForm.username.data = user.username
		updateForm.email.data = user.email
	return render_template('profile.html', title='Profile', form=updateForm, postForm=postForm, eventForm=eventForm, user=user, posts=posts, comments=comments, events=events)


@users.route("/user/<string:username>/promote", methods=['POST'])
@login_required
def promote_user(username):
	user = User.query.filter_by(username=username).first()

	if not user:
		return jsonify({'message': 'No user found', 'success' : False})

	if user.user_role == 'visitor':
		promoteToValue = 'member'
	elif user.user_role == 'member':
		promoteToValue = 'admin'
	else:
		promoteToValue = 'visitor'
	
	user.user_role = promoteToValue
	user.subscribedTo = promoteToValue
	
	db.session.commit()

	flash('User has been promoted!', 'success')
	return redirect(url_for('members.membership'))


@users.route("/user/<string:username>/demote", methods=['POST'])
@login_required
def demote_user(username):
	user = User.query.filter_by(username=username).first()

	if not user:
		return jsonify({'message': 'No user found', 'success' : False})

	if user.user_role == 'admin':
		demoteToValue = 'member'
	elif user.user_role == 'member':
		demoteToValue = 'visitor'
	else:
		demoteToValue = 'visitor'

	user.user_role = demoteToValue
	user.subscribedTo = demoteToValue

	db.session.commit()

	flash('User has been demoted!', 'success')
	return redirect(url_for('members.membership'))


@users.route("/user/<string:username>/delete", methods=['POST'])
def delete_user(username):
	user = User.query.filter_by(username=username).first()

	if not user:
		return jsonify({'message': 'No user found', 'success' : False})

	db.session.delete(user)
	db.session.commit()

	flash('User has been deleted!', 'success')
	return redirect(url_for('members.membership'))


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	reqPassWForm = RequestResetForm()
	if reqPassWForm.validate_on_submit():
		user = User.query.filter_by(email=reqPassWForm.email.data).first()
		send_reset_email(user)
		flash('An email has been sent with instruction to reset your password', 'info')
		return redirect(url_for('users.login'))
	return render_template('reset_request.html', title='Reset Password', form=reqPassWForm)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = User.verify_reset_token(token)
	if user is None:
		flash('That is an invalid or expired token', 'warning')
		return redirect(url_for('users.reset_request'))
	resetForm = ResetPasswordForm()
	if resetForm.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(resetForm.password.data).decode('utf-8')
		user.password = hashed_password
		db.session.commit()
		flash('Your password has been updated! You are now able to log in', 'success')
		return redirect(url_for('users.login'))
	return render_template('reset_token.html', title='Reset Password', form=resetForm)

mpa_admin_app/templates/add_event.html
<div id="addEvent" class="collapse">
  <div class="content-section mt-3">
    <form method="POST" action="{{ url_for('events.new_event') }}" enctype="multipart/form-data">
      <h3 class="mb-3 mt-1">Add Event</h3>
      <input type="hidden" name="path" value="{{ request.path }}"/>
      <!-- we need to pass this hiddent_tag method because what this does, it adds a CSRF Token (Cross-Site Request Forgery Token) -->
      {{  eventForm.hidden_tag() }}
        <fieldset class="form-group">
  
          <div class="form-group">
            {{ eventForm.title.label(class="form-control-label") }}
            {% if eventForm.title.errors %}
              {{ eventForm.title(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in eventForm.title.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ eventForm.title(class="form-control form-control-lg") }}
            {% endif %}
          </div>
  
          <div class="form-group">
            {{ eventForm.content.label(class="form-control-label") }}
            {% if eventForm.content.errors %}
              {{ eventForm.content(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in eventForm.content.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ eventForm.content(class="form-control form-control-lg") }}
            {% endif %}
          </div>
  
          <div class="form-group">
            {{ eventForm.event_date.label(class="form-control-label") }}
            {% if eventForm.event_date.errors %}
              {{ eventForm.event_date(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in eventForm.event_date.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ eventForm.event_date(class="form-control form-control-lg") }}
              <small class="text-muted">
                Accepted format: YYYY-MM-DD
              </small>
            {% endif %}
          </div>
  
        </fieldset>
        <div class="form-group">
          {{ eventForm.submit(class="btn btn-outline-info") }}
        </div>
    </form>
  </div>
</div>

mpa_admin_app/templates/add_post.html
<div id="addPost" class="collapse">
  <div class="content-section mt-3">
    <form method="POST" action="{{ url_for('posts.new_post') }}" enctype="multipart/form-data">
      <h3 class="mb-3 mt-1">Add Post</h3>
      <input type="hidden" name="path" value="{{ request.path }}"/>
      <!-- we need to pass this hiddent_tag method because what this does, it adds a CSRF Token (Cross-Site Request Forgery Token) -->
      {{  postForm.hidden_tag() }}
        <fieldset class="form-group">
  
          <div class="form-group">
            {{ postForm.title.label(class="form-control-label") }}
            {% if postForm.title.errors %}
              {{ postForm.title(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in postForm.title.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ postForm.title(class="form-control form-control-lg") }}
            {% endif %}
          </div>
  
          <div class="form-group">
            {{ postForm.content.label(class="form-control-label") }}
            {% if postForm.content.errors %}
              {{ postForm.content(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in postForm.content.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ postForm.content(class="form-control form-control-lg") }}
            {% endif %}
          </div>
  
          <div class="form-group">
            {{ postForm.code_snippet.label(class="form-control-label") }}
            {% if postForm.code_snippet.errors %}
              {{ postForm.code_snippet(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in postForm.code_snippet.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ postForm.code_snippet(class="form-control form-control-lg") }}
            {% endif %}
          </div>
        </fieldset>
        <div class="form-group">
          {{ postForm.submit(class="btn btn-outline-info") }}
        </div>
    </form>
  </div>
</div>

mpa_admin_app/templates/create_post.html
{% extends "_shared/_layout.html" %}
{% block content %} 

  <div class="content-section">
    <form method="POST" action="">
      <!-- we need to pass this hiddent_tag method because what this does, it adds a CSRF Token (Cross-Site Request Forgery Token) -->
      {{  form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">{{ legend }}</legend>

        <div class="form-group">
          {{ form.title.label(class="form-control-label") }}
          {% if form.title.errors %}
            {{ form.title(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.title.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.title(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.content.label(class="form-control-label") }}
          {% if form.content.errors %}
            {{ form.content(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.content.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.content(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.code_snippet.label(class="form-control-label") }}
          {% if form.code_snippet.errors %}
            {{ form.code_snippet(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.code_snippet.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.code_snippet(class="form-control form-control-lg") }}
          {% endif %}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </form>
  </div>

{% endblock content %}

mpa_admin_app/templates/create_role.html
{% extends "_shared/_layout.html" %}
{% block content %} 

  <div class="content-section">
    <form method="POST" action="">
      <!-- we need to pass this hiddent_tag method because what this does, it adds a CSRF Token (Cross-Site Request Forgery Token) -->
      {{  form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">{{ legend }}</legend>

        <div class="form-group">
          {{ form.title.label(class="form-control-label") }}
          {% if form.title.errors %}
            {{ form.title(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.title.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.title(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.description.label(class="form-control-label") }}
          {% if form.description.errors %}
            {{ form.description(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.description.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.description(class="form-control form-control-lg") }}
          {% endif %}
        </div>

      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </form>
  </div>

{% endblock content %}

mpa_admin_app/templates/event.html
<article class="media content-section">
	<img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + event.author.image_file) }}">
	<div class="media-body">
    <div class="article-metadata" style="height: 40px;">
      <span style="vertical-align: sub;">
        <a class="mr-2" href="{{ url_for('users.profile', id=event.author.id) }}">{{ event.author.username }}</a>
        <small class="text-muted">Event Date: {{ event.event_date.strftime('%Y-%m-%d') }}</small>
      </span>
      {% if event.author == current_user %}
        <span style="float:right;">
          <a class="btn btn-info btn-sm mt-1 mb-1" href="{{ url_for('events.update_event', event_id=event.id) }}"><span class="fas fa-pencil-alt"></span></a>
          <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteEventModal"><span class="fas fa-trash-alt"></span></button>
        </span>
      {% endif %}
		</div>
		<h2 class="article-title">{{ event.title }}</h2>
    <p class="article-content">{{ event.content }}</p>
    {% include 'modals/delete_event_modal.html' %}
	</div>
</article>

mpa_admin_app/templates/login.html
{% extends "_shared/_layout.html" %}
{% block content %} 

  <div class="content-section">
    <form method="POST" action="">
      <!-- we need to pass this hiddent_tag method because what this does, it adds a CSRF Token (Cross-Site Request Forgery Token) -->
      {{  form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Log In</legend>

        <div class="form-group">
          {{ form.username.label(class="form-control-label") }}
          {% if form.username.errors %}
            {{ form.username(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.username.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.username(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.password.label(class="form-control-label") }}
          {% if form.password.errors %}
            {{ form.password(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.password(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        
        <!-- <div class="form-check">
          {{ form.remember(class="form-check-input") }}
          {{ form.remember.label(class="form-check-label") }}
        </div> -->
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
          <small class="text-muted ml-2">
            <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
          </small>
      </div>
    </form>
  </div>
  <div class="border-top pt-3">
    <small class="text-muted">
      Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
    </small>
  </div>

{% endblock content %}

mpa_admin_app/templates/post.html
<article class="media content-section">
  <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
  <div class="media-body">
    <div class="article-metadata" style="height: 40px;">
      <span style="vertical-align: sub;">
        <a class="mr-2" href="{{ url_for('users.profile', id=post.author.id) }}">{{ post.author.username }}</a>
        <small class="text-muted">Posted on: {{ post.date_posted.strftime('%Y-%m-%d %H:%M') }}</small>
      </span>
      {% if post.author == current_user %}
        <span style="float:right;">
          <a class="btn btn-info btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}"><span class="fas fa-pencil-alt"></span></a>
          <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal"><span class="fas fa-trash-alt"></span></button>
        </span>
      {% endif %}
    </div>
    <h2>{{ post.title }}</h2>
    <p>{{ post.content }}</p>
    {% if post.code_snippet %}
      <pre class="prettyprint">{{ post.code_snippet }}</pre>
    {% endif %}

    {% for comment in comments %}
      {% if comment.post_id == post.id %}
        {% include 'comments/comment.html' %}
        {% include 'modals/delete_comment_modal.html' %}
      {% endif %}
    {% endfor %}
    
    {% if current_user.is_authenticated %}
      {% include 'comments/write_comment.html' %}
    {% endif %}

    {% include 'modals/delete_post_modal.html' %}
  </div>
</article>